$ErrorActionPreference = "Stop"

New-Item -ItemType Directory -Force -Path "stitch_screens"

Write-Host "Downloading Screen 1: Halaman Login"
curl.exe -L -o "stitch_screens/1_Halaman_Login.png" "https://lh3.googleusercontent.com/aida/ADBb0ugtj-rlA3qJdEfw9EUszXGV18F3iEA3lCNft4tIQs6aPZDISLXsH_3RGJaV7BOs5uNtvRKAFVCC3OgmlveY751vrpazexZktVj4Pqg6Plx_25dXFyOHaXOnITL4Jz-YtWYv4xjYXK3HWhkqnv9fBSDZP_Pz1PRMTLhidtOES30nqHm7MIQfHV4uZ8OVPU2_WHyam35zNzM8UwYqSuJD0mJwHxNzbJJq8dXrCJsIjYfmQLbAMWXGCHafCdY"
curl.exe -L -o "stitch_screens/1_Halaman_Login.html" "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2ZiMDMwZmRlZmNhYzRiODRiZjY5ZmZhZmFjZTRhYzgxEgsSBxC9jIGq_xIYAZIBIwoKcHJvamVjdF9pZBIVQhMzMzU2NDI3NTQ4NDI1NDk2NTI2&filename=&opi=89354086"

Write-Host "Downloading Screen 2: Manajemen Anggota"
curl.exe -L -o "stitch_screens/2_Manajemen_Anggota.png" "https://lh3.googleusercontent.com/aida/ADBb0uhzjfM8WebwLMGa71_ShVSUZetZ0pFR6uT7GlOhzGRqmiNSDvzX-mMVB70ueQ7ZPpmG3riU1piidZxkFyodjiMtYlIpIXguEN0sgIyBLqYbxWQ2i_ZDjJczwBukY0CQV6jIwvq9_eNqlCWQ-h6gwNYJQmq_79DuqLzbemOn5tPFGY2PQhqSfU62BiAep5V26jbdhjuLOFBkFiqS5OEB8D5pFgYJLmbRldo7uBlF0zYBK9Q3w3yYGCuVFSE"
curl.exe -L -o "stitch_screens/2_Manajemen_Anggota.html" "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzI5MjU3Njk4MzY0MTQ0NzE4YmMyNmFhZWMzYzM5MGEwEgsSBxC9jIGq_xIYAZIBIwoKcHJvamVjdF9pZBIVQhMzMzU2NDI3NTQ4NDI1NDk2NTI2&filename=&opi=89354086"

Write-Host "Downloading Screen 3: Dashboard Utama (Updated)"
curl.exe -L -o "stitch_screens/3_Dashboard_Utama_Updated.png" "https://lh3.googleusercontent.com/aida/ADBb0uhtpsjN2UYmGfYBNjsUB-YtolyQQmpwEcaA5tSWYHYMl3bm44jlUW9kc8xFfOBaH6tyZqM1NB-XDJMZbuKJpbHO6PefBMjtrSJJc4HMjk7_b1PiZZbvzvM8CjLAvd6v8vQJOp_T2La7uh_6RgvoKDnwesmcBCt27OgnySMwdl-oM69TVJebbJfvknjrP0d9b9Uq7Bz44gW-WBjo2LPtuEOrmu8kAXLNsPSQc4SDlPUvAnTssHRx7YprYAk"
curl.exe -L -o "stitch_screens/3_Dashboard_Utama_Updated.html" "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2Y5OGY1MTU5ZGIxNTRmM2FiOTQ2NWVlMjRiY2M3ZmUzEgsSBxC9jIGq_xIYAZIBIwoKcHJvamVjdF9pZBIVQhMzMzU2NDI3NTQ4NDI1NDk2NTI2&filename=&opi=89354086"

Write-Host "Downloading Screen 4: Halaman Absensi (Updated)"
curl.exe -L -o "stitch_screens/4_Halaman_Absensi_Updated.png" "https://lh3.googleusercontent.com/aida/ADBb0uhgEArXvZzI1fAR0Op0WvwhkdMW_yEyMzgYvebkbRGuLTsyFw1YVq5LC_ohbp4_LENe7Xdx2hi4Jc66Ppt3-xHwqwo5HxE2P0QxaZiarI-rRcHtqzJR6nFnwgUj0osl9QbVai7i17bqxjwTUMNStK6cnjjtsQ58y5LWoHVpRpHw-qzVA5J97ZPgm3o16iAvDjscHx_zRBb1iSG0Kk7XLeJyicSNf0hhSEY6PrMobPeniAWRUZtWuIbxwqo"
curl.exe -L -o "stitch_screens/4_Halaman_Absensi_Updated.html" "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2UxYTFiMDUxMTEyMDQ4NGZhYjNmMzBlOTM5ZTQzMTVmEgsSBxC9jIGq_xIYAZIBIwoKcHJvamVjdF9pZBIVQhMzMzU2NDI3NTQ4NDI1NDk2NTI2&filename=&opi=89354086"

Write-Host "Downloading Screen 5: Riwayat Kehadiran Saya"
curl.exe -L -o "stitch_screens/5_Riwayat_Kehadiran_Saya.png" "https://lh3.googleusercontent.com/aida/ADBb0ujCJJ86d2M27386cZwGewaZJO6j5mYgPT4pqBUs9GrUEfYTHaFqmTPHsZ92YE8RLaV-Zgyu8TiAfACDrN00IYXgJ3fgd3aCKHio8msKbLBrAXCUZ__IgU8oWPFVrUwJizHKd6ffq7Xr_xHsoaUjVxNq4rMWkZV30CcoMK8_uWJJ873na4GN4QvE5J7u3IwXamIwMqDaOZwZ9lrLWmjKz25xP3JxTQksampiJYCF4nAvBG_rFPdA3Ms8B84"
curl.exe -L -o "stitch_screens/5_Riwayat_Kehadiran_Saya.html" "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzBkZThmMTkzZDEyMTQzYWI4ZDMyM2VjOWU4NzQ3OWM4EgsSBxC9jIGq_xIYAZIBIwoKcHJvamVjdF9pZBIVQhMzMzU2NDI3NTQ4NDI1NDk2NTI2&filename=&opi=89354086"

Write-Host "Downloading Screen 6: Check-in Mandiri Anggota"
curl.exe -L -o "stitch_screens/6_Check_in_Mandiri_Anggota.png" "https://lh3.googleusercontent.com/aida/ADBb0uh44X9GPz4AL6Glq-IrBSiYzLr0ADQIO-wzgD0AUx8NHCbwwUDprk6lH78gm5T6DwDGuI6-AYLziGXDR2T6ssGDPFRCqTyIg57dwkqo71s78eYAGn5e-uDQfP1qBlbBs1toxX4MO2c07d5KESK_ezPoSaih1DMau5qhn9o0Td_g6zfTxapYFWRrrPhzcAnw-TVvqzftnkzDcldbzSS3c1r4-8Vstgwu6N-esEu5IPSFe6yl84DBl2kfN44"
curl.exe -L -o "stitch_screens/6_Check_in_Mandiri_Anggota.html" "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzEzMjM4NWExYTg5MDRkMGQ4ZWI0Yjg1ODgyOThmMWIzEgsSBxC9jIGq_xIYAZIBIwoKcHJvamVjdF9pZBIVQhMzMzU2NDI3NTQ4NDI1NDk2NTI2&filename=&opi=89354086"

Write-Host "Downloading Screen 7: Dashboard Anggota"
curl.exe -L -o "stitch_screens/7_Dashboard_Anggota.png" "https://lh3.googleusercontent.com/aida/ADBb0ugNbNvXVP7Ihxtysq-1V8ezn4eijAn6UWlfsUbnTWyQVf-SoQY0uJEQBpStXOWjDTuhHive3eUj2sKtBhZZgdd7USGEGB1d5x_-kC4op4--QPh_jHkbgFOk47dkkgPu5rqrER9942wRGscI-gMFrZk3xymJ_wgEjN9SuqCCTbqHKvxMuCU_bTeKo5-6wQDbglTOOelioR_zQkNFfvzLzXpQ7m30NXZ4dXo08mmdnY2g6wuV66GETbFC8Ug"
curl.exe -L -o "stitch_screens/7_Dashboard_Anggota.html" "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2IyYmUzZGUwZmY3ODRmZWNiMmQ5MzM1YTQ5MTg0YjNhEgsSBxC9jIGq_xIYAZIBIwoKcHJvamVjdF9pZBIVQhMzMzU2NDI3NTQ4NDI1NDk2NTI2&filename=&opi=89354086"

Write-Host "Downloading Screen 8: Manajemen Anggota (Updated)"
curl.exe -L -o "stitch_screens/8_Manajemen_Anggota_Updated.png" "https://lh3.googleusercontent.com/aida/ADBb0uiK5oUQR7DvYx0z6eHhPeAeOSi5B-Ep8uCD67tYo-BdAZE6H7X3fwb2xAJcCbhHRZtFhB24cFHWvFasFBFSAfh9ROi0JX865SBcqEjtXYaae_2LA3I8JCpkR_6l2O98rpFGtXSO7QbucQWe_HgahBZZy1bcehPv6dpP1IBjh9bILn8CUNGnUiUqYpDIxNW3l4eiP7FMeYNxOrDOKriwWg39JrPY5H8QFbHJEPc_v4s2kq8aIhdiVInAyw"
curl.exe -L -o "stitch_screens/8_Manajemen_Anggota_Updated.html" "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzg2YmZhNmQyMWEzMDQ5MWViZjdmMzRjZDZmOTFhZjdmEgsSBxC9jIGq_xIYAZIBIwoKcHJvamVjdF9pZBIVQhMzMzU2NDI3NTQ4NDI1NDk2NTI2&filename=&opi=89354086"

Write-Host "Download Complete"
